### ISSUE TITLE
Not working on SoD

### ISSUE THREAD

**Issue by BigBear-92** [WRMSRwasTaken/ElvUI_MirrorAbsorb#1]
I downloaded the folder, put it in the interface/addons folder and I can see a "ElvUI_MirrorAbsorb Version 1.0 loaded." message in the chat when loading in, but it does not seem to work and I do not find it listed in the ElvUI plugins section.
I may very well be doing something wrong, but i'm also wondering if it's not working due to being on SoD.

**Comment by WRMSRwasTaken** [comment]
Hi,

I haven't tested this for SoD (I am only playing retail) :(

Looking at the code, the code my plugin hooks does not differentiate between Classic or Retail (DF) mode because I am relying on values ElvUI is using internally... but what I am seeing is that ElvUI doesn't even register the events for displaying shields for Classic WoW: https://github.com/tukui-org/ElvUI/blob/3bd919ba6f8a061678ab3181bbd1c501bb343271/ElvUI_Libraries/Core/oUF/elements/healthprediction.lua#L268

Looking at the Wowpedia for the event ElvUI uses, it has been only added in Patch 5.2 (MoP): https://wowpedia.fandom.com/wiki/UNIT_ABSORB_AMOUNT_CHANGED

Also the HealComm Mode (which is active on Classic) only seems to display values for heals and no absorbs: https://github.com/tukui-org/ElvUI/blob/3bd919ba6f8a061678ab3181bbd1c501bb343271/ElvUI_Libraries/Core/oUF/elements/healthprediction.lua#L242

So unfortunately there's nothing I can do here (if I understood everything correctly) :( It really seems that ElvUI doesn't display shields in Classic mode at all, sorry!
